### ISSUE TITLE
Why Hadoop_Home is not defined?

### ISSUE THREAD

**Issue by robyle** [SaschaDittmann/HdfsExplorer#2]
![image](https://user-images.githubusercontent.com/11662528/37453566-023e9e3c-2873-11e8-8d57-1e8c46e5da9d.png)

I get the test hdfs connection error, How should I to slove it?

**Comment by SaschaDittmann** [comment]
You need to install the hadoop libraries locally and add a reference in the HADOOP_HOME env. variable.
